#!/usr/bin/python
# filter: INPUT/FORWARD/OUTPUT
# nat: PREROUTING/POSTROUTING/OUTPUT
# mangle: PREROUTING/INPUT/FORWARD/OUTPUT/POSTROUTING
#  PREROUTING
#   -> fw-host-pre-prerouting-in  (host: pre-prerouting-in)
#   -> fw-interface-prerouting-in
#   -> fw-<interface>-prerouting-in  (interface: prerouting-in)
#   -> fw-host-post-in  (host: post-prerouting-in)
#  INPUT 
#   -> fw-host-pre-in  (host: pre-in)
#   -> fw-interface-in 
#   -> fw-<interface>-in (interface: in)
#   -> fw-host-post-in (host: post-in)
#  FORWARD 
#   -> fw-host-pre-forward  (host: pre-forward)
#   -> fw-interface-forward-in
#   -> fw-<interface>-forward-in  (interface: forward-in)
#   -> fw-interface-forward-out 
#   -> fw-<interface>-forward-out  (interface: forward-out)
#   -> fw-post-forward  (host: post-forward)
#  OUTPUT 
#   -> fw-host-pre-out  (host: pre-out)
#   -> fw-interface-out 
#   -> fw-<interface>-out  (interface: out)
#   -> fw-host-post-out (host: post-out)
#  POSTROUTING
#   -> fw-host-pre-postrouting-out  (host: pre-postrouting-out)
#   -> fw-interface-postrouting-out
#   -> fw-<interface>-prerouting-out (interface: postrouting-out)
#   -> fw-host-post-postrouting-out (host: post-postrouting-out)

import fwall.firewall
import sys

fwall.firewall.main(sys.argv)
